modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="rubies"
version="1.0.0"
displayName="Rubies"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pifase"
description='''
Adds rubies to Minecraft
'''

[[dependencies.rubies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




